DROP TABLE IF EXISTS push_tokens CASCADE;
DROP TABLE IF EXISTS otp_codes CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS masters CASCADE;
DROP TABLE IF EXISTS programs CASCADE;
DROP VIEW IF EXISTS v_bookings_full;
DROP VIEW IF EXISTS v_slots_with_program;